# -*- coding: utf-8 -*-
"""NLP-5_Fine-Tuning_BERT_for_POS_Tagging&Chunking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwMT1O1gyNrsdfPozgtlGFsanLhq1dbO

**Fine-tune a transformer model (BERT/DistilBERT) to perform: Part-of-Speech (POS) Tagging- Chunking**

**1. Dataset Selection**
Option 1: Universal Dependencies (POS Tagging)

Used for Part-of-Speech tagging.

Common POS Labels:

NOUN
VERB
ADJ
ADV
PRON
DET
ADP
NUM
CONJ
PRT
PUNCT
X
Option 2: CoNLL-2003 (Chunking)

Used for Phrase Chunking.

Chunk Labels:

B-NP → Beginning of Noun Phrase
I-NP → Inside Noun Phrase
B-VP → Beginning of Verb Phrase
I-VP → Inside Verb Phrase
B-PP → Beginning of Preposition Phrase
I-PP → Inside Preposition Phrase
O → Outside any chunk

Deliverable Example:

Dataset Name: CoNLL-2003
Task: Chunking
Labels: B-NP, I-NP, B-VP, I-VP, B-PP, I-PP, O

**2. Data Preprocessing**
Steps:
Load dataset
Tokenize using BERT tokenizer
Align labels with tokens
Handle subwords
Use -100 for special tokens
Label Alignment Logic

When a word splits into subwords:

playing → play ##ing
VERB → VERB VERB
"""

!pip install transformers datasets seqeval evaluate -q

from datasets import load_dataset

dataset = load_dataset("conll2003")
dataset

from huggingface_hub import login
login("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")

import os
os.environ["HF_TOKEN"] = "hf_xxxxxxxxxxxxxxxxxxxxx"

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

label_list = dataset["train"].features["ner_tags"].feature.names

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        padding="max_length",
        max_length=128,   # Reduce length here
        is_split_into_words=True
    )

    labels = []

    for i in range(len(examples["tokens"])):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        label_ids = []
        previous_word_idx = None

        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(examples["ner_tags"][i][word_idx])
            else:
                label_ids.append(examples["ner_tags"][i][word_idx])

            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

tokenized_dataset = dataset.map(
    tokenize_and_align_labels,
    batched=True
)

tokenized_dataset

small_train_dataset = tokenized_dataset["train"].select(range(1000))
small_eval_dataset = tokenized_dataset["validation"].select(range(300))

from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    "bert-base-cased",
    num_labels=len(label_list)
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=50,
    save_steps=500
)

from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    data_collator=data_collator
)

trainer.train()

import numpy as np
import evaluate

metric = evaluate.load("seqeval")

predictions, labels, _ = trainer.predict(small_eval_dataset)
predictions = np.argmax(predictions, axis=2)

true_labels = [
    [label_list[l] for l in label if l != -100]
    for label in labels
]

true_predictions = [
    [label_list[p] for (p, l) in zip(pred, label) if l != -100]
    for pred, label in zip(predictions, labels)
]

results = metric.compute(
    predictions=true_predictions,
    references=true_labels
)

print("Precision:", results["overall_precision"])
print("Recall:", results["overall_recall"])
print("F1 Score:", results["overall_f1"])

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

true_labels_flat = []
true_predictions_flat = []

for pred, lab in zip(predictions, labels):
    for p, l in zip(pred, lab):
        if l != -100:
            true_labels_flat.append(l)
            true_predictions_flat.append(p)

cm = confusion_matrix(true_labels_flat, true_predictions_flat)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_list)
disp.plot(xticks_rotation=90)
plt.show()

from sklearn.metrics import classification_report

print(classification_report(
    true_labels_flat,
    true_predictions_flat,
    target_names=label_list
))

from transformers import pipeline

ner_pipeline = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokenizer
)

print(ner_pipeline("John works at Google in California"))



from transformers import pipeline

ner_pipeline = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokenizer
)

sentence = "John works at Google in California"
result = ner_pipeline(sentence)

for r in result:
    print(r["word"], "->", r["entity"])

model.save_pretrained("bert-ner-model")
tokenizer.save_pretrained("bert-ner-model")

