# -*- coding: utf-8 -*-
"""T2_LangChain_Deep_Technical_Blog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12o7ZP0S_IEWuEMws5S9x5EQiNnSjPG4m
"""

!pip uninstall -y langchain langchain-openai requests
!pip install requests==2.32.4
!pip install langchain langchain-openai langchain-community faiss-cpu tiktoken python-dotenv

from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline

# Load free model
pipe = pipeline("text-generation", model="gpt2")

llm = HuggingFacePipeline(pipeline=pipe)

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate.from_template(
    "Explain {topic} in simple terms"
)

chain = prompt | llm

response = chain.invoke({"topic": "Artificial Intelligence"})
print(response)

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain-huggingface

from langchain_huggingface import HuggingFacePipeline

"""**Clean LLM Setup**"""

from langchain_huggingface import HuggingFacePipeline
from transformers import pipeline

pipe = pipeline("text-generation", model="gpt2")

llm = HuggingFacePipeline(pipeline=pipe)

"""**Clean Prompt + Chain**"""

pipe = pipeline(
    "text-generation",
    model="gpt2",
    max_new_tokens=100,
    temperature=0.7
)

llm = HuggingFacePipeline(pipeline=pipe)

# Claen Output (Trim Garbage Text)
def clean_output(text):
    return text.split("\n")[0]

result = chain.invoke({"topic": "Artificial Intelligence"})
print(clean_output(result))

# Memory (Improved Version)
chat_history = []

def chat(user_input):
    chat_history.append(f"User: {user_input}")

    context = "\n".join(chat_history)

    prompt = f"""
    Conversation:
    {context}

    AI:
    """

    response = llm.invoke(prompt)
    response = clean_output(response)

    chat_history.append(f"AI: {response}")

    return response

print(chat("Hi, I am Murali"))
print(chat("What is my name?"))

# Tool (Calculator)
def calculator(query):
    try:
        return str(eval(query))
    except:
        return "Invalid expression"

print(calculator("45*2+10"))

# Agent (Better Logic)
def agent(query):
    if any(char.isdigit() for char in query):
        return calculator(query)
    else:
        return clean_output(llm.invoke(query))

print(agent("What is 25 * 4 + 10?"))
print(agent("Explain LangChain"))

# Document Loader
from langchain_community.document_loaders import TextLoader

with open("knowledge.txt", "w") as f:
    f.write("""
    LangChain is a framework for building applications using Large Language Models.
    It supports chains, memory, agents, and retrieval-based systems.
    """)

loader = TextLoader("knowledge.txt")
documents = loader.load()

# Text Splitting
from langchain_text_splitters import CharacterTextSplitter

splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=20)
docs = splitter.split_documents(documents)

# Vector Store
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings()

vectorstore = FAISS.from_documents(docs, embeddings)

# RAG System
def rag(query):
    docs = vectorstore.similarity_search(query)
    context = docs[0].page_content

    prompt = f"""
    Answer using context:

    {context}

    Question: {query}
    """

    return clean_output(llm.invoke(prompt))

print(rag("What is LangChain?"))

